on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-storage-and-cdn.yml'
      - 'storage-and-cdn/**'

name: Deploy Storage and CDN

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-storage-and-cdn"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./storage-and-cdn/template.json
        parameters: ./storage-and-cdn/parameters.json