on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-app-services.yml'
      - 'app-services/**'

name: Deploy App Services

jobs:
  deploy-edge:
    name: Deploy Edge
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-app-services-edge"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-services/template.json
        parameters: './app-services/parameters-edge.json
          sites_default_assets_reload_token=${{ secrets.SHARPLAB_ASSETS_RELOAD_TOKEN_EDGE }}
          sites_default_github_client_id=${{ secrets.SHARPLAB_GITHUB_CLIENT_ID_EDGE }}
          sites_default_github_client_secret=${{ secrets.SHARPLAB_GITHUB_CLIENT_SECRET_EDGE }}
          sites_container_experiment_key=${{ secrets.SHARPLAB_CONTAINER_EXPERIMENT_KEY }}'

  test-edge:
    name: Test Edge
    runs-on: ubuntu-latest
    needs: deploy-edge
    steps:
    - uses: actions/checkout@main
    - name: '[Edge] Run ./app-services/Test-AppServices.ps1'
      run: ./app-services/Test-AppServices.ps1 ./app-services/parameters-edge.json
      shell: pwsh

  deploy-main:
    name: Deploy Main
    runs-on: ubuntu-latest
    needs: test-edge
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-app-services-main"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-services/template.json
        parameters: './app-services/parameters-main.json
          sites_default_assets_reload_token=${{ secrets.SHARPLAB_ASSETS_RELOAD_TOKEN_MAIN }}
          sites_default_github_client_id=${{ secrets.SHARPLAB_GITHUB_CLIENT_ID_MAIN }}
          sites_default_github_client_secret=${{ secrets.SHARPLAB_GITHUB_CLIENT_SECRET_MAIN }}
          sites_container_experiment_key=${{ secrets.SHARPLAB_CONTAINER_EXPERIMENT_KEY }}'

  test-main:
    name: Test Main
    runs-on: ubuntu-latest
    needs: deploy-main
    steps:
    - uses: actions/checkout@v4
    - name: 'Run ./app-services/Test-AppServices.ps1'
      run: ./app-services/Test-AppServices.ps1 ./app-services/parameters-main.json
      shell: pwsh