on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-container-host.yml'
      - 'container-host/**'
  workflow_dispatch:

name: Deploy Container Host

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-container-host"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./container-host/template.json
        parameters: './container-host/parameters.json
          virtualMachines_adminUsername=${{ secrets.CONTAINER_HOST_ADMIN_USERNAME }}'

    # TODO: Fail build if this fails -- currently it always reports success
    - name: "VM: Initialize-ContainerHost.ps1"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.23.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          telemetry_key=$(az monitor app-insights component show \
            --app sharplab-container-host-insights \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --query instrumentationKey \
            --output tsv)
          echo "::add-mask::${telemetry_key}"

          authorization_token=$(az keyvault secret show \
            --name ContainerHostAuthorizationToken \
            --vault-name sharplab \
            --query value \
            --output tsv)
          echo "::add-mask::${authorization_token}"

          az vm run-command invoke \
            --command-id RunPowerShellScript \
            --name sharplab-container-host \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --scripts @container-host/Initialize-ContainerHost.ps1 \
            --parameters "TelemetryKey=${telemetry_key}" \
                         "AuthorizationToken=${authorization_token}"