on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-configuration.yml'
      - 'configuration/**'

name: Deploy Configuration

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: '[Edge] Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-configuration-edge"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./configuration/template.json
        parameters: ./configuration/parameters-edge.json

    - name: '[Main] Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        deploymentName: "sharplab-configuration-main"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./configuration/template.json
        parameters: ./configuration/parameters-main.json