on:
  push:
    branches:
      - main

name: Deploy Edge

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - uses: azure/powershell@v1
      name: Run ./Update-CertificateThumbprint.ps1
      with:
        inlineScript: |
          $ErrorActionPreference = 'Stop'
          ./Update-CertificateThumbprint.ps1 ./app-services/parameters-edge.json
        azPSVersion: '3.1.0'

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-services/template.json
        parameters: ./app-services/parameters-edge.json