on:
  workflow_dispatch

name: Deploy App Services (Main)

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - uses: azure/powershell@v1
      name: Run ./app-services/Update-CertificateThumbprint.ps1
      with:
        inlineScript: |
          $ErrorActionPreference = 'Stop'
          ./app-services/Update-CertificateThumbprint.ps1 ./app-services/parameters-main.json
        azPSVersion: '3.1.0'

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-services/template.json
        parameters: ./app-services/parameters-main.json

    - run: ./app-services/Test-AppServices.ps1 ./app-services/parameters-main.json
      shell: pwsh