on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-app-insights.yml'
      - 'app-insights/**'

name: Deploy App Insights

jobs:
  deploy-edge:
    name: Deploy Edge
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        scope: 'resourcegroup'
        deploymentName: "sharplab-app-insights-edge"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-insights/template.json
        parameters: './app-insights/parameters-edge.json'

  deploy-main:
    name: Deploy Main
    runs-on: ubuntu-latest
    needs: deploy-edge
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run ashmind/arm-deploy@main'
      uses: ashmind/arm-deploy@main
      with:
        scope: 'resourcegroup'
        deploymentName: "sharplab-app-insights-main"
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./app-insights/template.json
        parameters: './app-insights/parameters-main.json'