on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-container-host.yml'
      - 'container-host/**'

name: Deploy Container Host

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./container-host/template.json
        parameters: ./container-host/parameters.json

    - name: 'Run az monitor app-insights component show'
      uses: azure/CLI@v1
      id: get_telemetry_key
      with:
        azcliversion: 2.23.0
        inlineScript: |
          telemetry_key = $(az monitor app-insights component show \
            --app sharplab-container-host-insights \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --query instrumentationKey \
            --output tsv)
          echo ::add-mask::$telemetry_key
          echo ::set-output name=telemetry_key::$telemetry_key

    # TODO: Fail build if this fails -- currently it always reports success
    - name: "VM: Initialize-ContainerHost.ps1"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.23.0
        inlineScript: |
          az vm run-command invoke \
            --command-id RunPowerShellScript \
            --name sharplab-container-host \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --scripts @container-host/Initialize-ContainerHost.ps1 \
            --parameters "AdminUserName=${{ secrets.CONTAINER_HOST_ADMIN_USERNAME }}" \
                         "AdminPassword=${{ secrets.CONTAINER_HOST_ADMIN_PASSWORD }}" \
                         "TelemetryKey=${{ steps.get_telemetry_key.outputs.telemetry_key }}"